// Autogenerated from Pigeon (v0.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FormatRequest;
@class FormatResponse;
@class ApiCountryWithPhoneCode;
@class GetAllSupportedRegionsReponse;

@interface FormatRequest : NSObject
@property(nonatomic, copy, nullable) NSString * phone;
@property(nonatomic, copy, nullable) NSString * region;
@end

@interface FormatResponse : NSObject
@property(nonatomic, copy, nullable) NSString * formatted;
@end

@interface ApiCountryWithPhoneCode : NSObject
@property(nonatomic, copy, nullable) NSString * phoneCode;
@property(nonatomic, copy, nullable) NSString * countryCode;
@property(nonatomic, copy, nullable) NSString * exampleNumberMobileNational;
@property(nonatomic, copy, nullable) NSString * exampleNumberFixedLineNational;
@property(nonatomic, copy, nullable) NSString * phoneMaskMobileNational;
@property(nonatomic, copy, nullable) NSString * phoneMaskFixedLineNational;
@property(nonatomic, copy, nullable) NSString * exampleNumberMobileInternational;
@property(nonatomic, copy, nullable) NSString * exampleNumberFixedLineInternational;
@property(nonatomic, copy, nullable) NSString * phoneMaskMobileInternational;
@property(nonatomic, copy, nullable) NSString * phoneMaskFixedLineInternational;
@property(nonatomic, copy, nullable) NSString * countryName;
@end

@interface GetAllSupportedRegionsReponse : NSObject
@property(nonatomic, strong, nullable) ApiCountryWithPhoneCode * _;
@property(nonatomic, strong, nullable) NSArray<ApiCountryWithPhoneCode *> * countries;
@end

/// The codec used by FlutterLibPhoneNumberApi.
NSObject<FlutterMessageCodec>* FlutterLibPhoneNumberApiGetCodec(void);

@protocol FlutterLibPhoneNumberApi
-(void)format:(nullable FormatRequest *)input completion:(void(^)(FormatResponse *_Nullable, FlutterError *_Nullable))completion;
-(void)getAllSupportedRegions:(void(^)(GetAllSupportedRegionsReponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FlutterLibPhoneNumberApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FlutterLibPhoneNumberApi> _Nullable api);

NS_ASSUME_NONNULL_END
